# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  newman: postman/newman@1.0.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - newman/newman-run:
          collection: https://api.getpostman.com/collections/10237495-ac5e27e2-3fbb-4a85-b86c-804a27d5b64b?apikey=PMAK-618d6b992cdd810046c2fa0b-30fc7a5967e7ba9bfb11a55e18e5262571
          environment: https://api.getpostman.com/environments/10237495-b9409f0b-70ff-445e-bbbe-649eeb05dc07?apikey=PMAK-618d6b992cdd810046c2fa0b-30fc7a5967e7ba9bfb11a55e18e5262571 
workflows:
  example-workflow:
    jobs:
      - example-job